Audio: Adapt to new `make` pattern + improve tests
solidjs-community/solid-primitives pull request #123
Opened 2022-05-07 16:47 UTC by davedbase

2022-05-07 19:15 UTC, thetarnav commented
Looks good.
The event-listener pkg could reduce the logic even more here.
Also, what about returning a Store, instead of an object of accessors in the new `createAudio`?

2022-05-07 19:41 UTC, davedbase commented
> Looks good. The event-listener pkg could reduce the logic even more here. Also, what about returning a Store, instead of an object of accessors in the new `createAudio`?

Yup, good suggestion!

2022-05-07 19:47 UTC, thetarnav commented
I've made a [`createStaticStore`](#https://github.com/solidjs-community/solid-primitives/blob/027231ae2981f490740a5f1d1101c9539624a5a6/packages/utils/src/index.ts#L323) for such smaller usecases btw.

2022-06-11 18:26 UTC, thetarnav requested changes
- [ ] fix tests
- [x] The docs could use some usage examples / types
It's hard to get an idea of what certain primitives will help you with, by just looking through the readme
- [x] There are few random console.logs in index.ts
- [x] expressions like these: `src instanceof Function ? src() : src` could be replaced with `access(src)`, since you already have utils package installed
- [x] Better types for event handlers
```ts
{
   [K in keyof HTMLMediaElementEventMap]?: (event: HTMLMediaElementEventMap[K]) => void;
}
// instead of 
{ [key: string]: EventListener }
```

2022-06-11 21:17 UTC, davedbase commented
@thetarnav I adjusted everything, just that pesky test that I have to track. Sigh.

2022-06-16 22:46 UTC, davedbase commented
@thetarnav tests are passing (wooohoo). Last review and we publish. Also there's a nice demo I put together

2022-06-17 20:52 UTC, thetarnav commented on packages/audio/test/index.test.ts
> +const testPath = 'https://github.com/solidjs-community/solid-primitives/blob/audio/packages/audio/dev/sample1.mp3?raw=true';
Better not delete that branch haha :D

2022-06-17 21:10 UTC, thetarnav approved these changes
Alright, the `server.ts` needed some corrections, but I took care of it. Looks good otherwise.

2022-06-17 21:23 UTC, davedbase commented
Shoot good point, I changed things last minute. Thanks for adjusting it! Going to merge and publish now.

2022-06-17 21:23 UTC, merged