fetch: new aggregation modifier
solidjs-community/solid-primitives pull request #207
Opened 2022-09-14 09:31 UTC by atk

In order to have infinite scrolling or similar solutions, you can use the new `withAggregation`modifier.

2022-09-15 15:10 UTC, thetarnav approved these changes
Alright this looks solid, you can merge anytime.
The only thing I'm thinking about is maybe a callback for a custom way to aggregate resources.
Like if you have a response structure like this:
```ts
type Response = {
   // field you'd want to overwrite
   tabId: string
   // field you'd want to concat
   posts: Post[]
}
```

2022-09-15 15:13 UTC, thetarnav requested changes
Oh, actually, I think you forgot about updating the server.ts export file :)

2022-09-26 18:45 UTC, atk commented
> Oh, actually, I think you forgot about updating the server.ts export file :)

Fixed that.

2022-09-26 19:51 UTC, thetarnav approved these changes

2022-09-26 19:52 UTC, merged