media: add toString ability to createBreakpoints
solidjs-community/solid-primitives pull request #404
Opened 2023-04-15 21:29 UTC by atk

2023-04-30 15:12 UTC, thetarnav requested changes
It seems fair to add this
But I don't think it should be done with `.toString()`, but with another, custom method that we can control the type of. Or better, a separate function like `getMathingBreakpoint()`.

![image](https://user-images.githubusercontent.com/24491503/235360751-6a020e7a-55aa-4c2d-860c-1d9827de9c00.png)

2023-04-30 15:12 UTC, thetarnav commented on packages/media/README.md
> +- [`sortBreakpoints`](#sortBreakpoints) - Sorts the breakpoints from small to large (to enable correct string coercion of the output of `createBreakpoints`).
it's a part of `createMediaQuery` API, not a standalone
```suggestion
```

2023-04-30 16:23 UTC, atk commented on packages/media/src/index.ts
> +  ) as Matches<T>;
Sorry. Using `forEach` instead of `reduce` to reduce an array is a pet peeve of mine.

2023-04-30 16:32 UTC, atk commented
> It seems fair to add this But I don't think it should be done with `.toString()`, but with another, custom method that we can control the type of. Or better, a separate function like `getMathingBreakpoint()`.

Why would we need to control the type of? What we want is a string, which is exactly what toString is supposed to deliver: some more or less useful string representation of the contents. Arrays set a precedent: try `[1,2,3]+''` – what you'll get is exactly what .toString() is meant for.

The most useful short string representation of our `matches` object is the name of the largest matching breakpoint. Thus, this is a prime example of .toString done right.

2023-04-30 16:35 UTC, thetarnav commented
We need to control the type, to be able to return `keyof T` instead of `string` to be able to use it as a index

2023-04-30 22:01 UTC, atk commented
Now I get your point. I'll consider it.

2023-05-01 20:13 UTC, atk commented
I thought long and hard about that and at the end, I settled on a "key" property, because that is the shortest name I could come up with that still conveys the intended meaning.

2023-05-01 20:37 UTC, atk commented
fixed it.

2023-05-02 09:43 UTC, merged