Add selectors
solidjs-community/solid-primitives pull request #518
Opened 2023-09-24 08:56 UTC by ryoid

Using [`createSelector`](https://www.solidjs.com/docs/latest/api#createselector) is good for a single values. I found that there are a lot of use cases for array selectors. I have been using this on a few projects and I think it would be a good addition to the library.

```tsx
const list: string[] = ["apple", "pear", "orange"]
const [selectedItems] = createSignal<string[]>(["apple"])
const isSelected = createArraySelector(selectedItems)

<For each={list}>
  {(item) => <li classList={{ active: isSelected(item) }}>{item}</li>}
</For>
```

Extending with a comparator function could be possible, but I decided to keep it simple. At that point it might be better to just create a custom selector directly.

2023-09-24 10:28 UTC, thetarnav requested changes
It's an interesting idea to have a package dedicated to the selector primitive. There might be other helpers this could include.
But right now I wouldn't advice anyone to use it with only `createArraySelector`, especially when it doesn't provide too much value.
Also I'm wondering if instead of exporting a `createSelector` wrapper, it would be better to just export the `(key, list) => list.includes(key)` part. Then one could compose it with the selector.
```ts
import { arrayIncludes } from "@solid-primitives/selector"

const isItemSelected = createSelector(selectedItems, arrayIncludes)
```

2023-09-24 10:28 UTC, thetarnav commented on packages/selectors/src/index.ts
> +  options?: { name?: string },
Better to reuse types from solid for the options (and any other type if possible), to show where it is coming from, and remove the need for updating the types when options in solid change.

2023-09-24 10:28 UTC, thetarnav commented on packages/selectors/package.json
> +  "name": "@solid-primitives/selectors",
prefer `selector` singular to match the rest of the packages

2023-09-24 10:28 UTC, thetarnav commented on packages/selectors/README.md
> +
Worth adding that it doesn't work when mutating the array:
https://playground.solidjs.com/anonymous/bfeda055-2f2c-465e-b438-ea9d671a4eb8

2023-09-24 10:28 UTC, thetarnav commented on packages/selectors/README.md
> +
Worth showing that the implementation is basically an alias to `createSelector` with `Array.includes`
```ts
const createArraySelector = source => createSelector(source, (key, list) => list.includes(key))
```
I don't want anyone to get an impression that it's not possible to do this with `createSelector`

2026-05-03 18:01 UTC, davedbase commented
Hey there! It's been quite a while since this was first introduced. We're working on Solid 2.0 migration right now and would like to consider this for the porting. Do you have time to finish off the current work for 1.0 or possibly support 2.0 directly?

2026-07-04 15:28 UTC, davedbase commented
Conducting general maintenance in preparation of Solid Primitives 2.0 release. The work here is valuable but may change with the resent push to Solid2 migration. Please resubmit a PR with the changes based on the `next` branch containing relevant changes. Thank you for your effort on this!

2026-07-04 15:28 UTC, closed without merging